### ISSUE TITLE
Using objects/classes in step definitions

### ISSUE THREAD

**Issue by Thegaram** [cucumber/cucumber.ml#5] opened 2018-03-15 14:10 UTC
I am trying to use a class/object in my test file.

```ocaml
class my_class =
  object
    ...
  end

let cucc = ...
    
module M : Cucumber.Lib.TEST_PLUGIN =
  struct
    let get_tests () = cucc
  end
  
let _ =
  Cucumber.Lib.plugin := Some (module M : Cucumber.Lib.TEST_PLUGIN)
```

This compiles successfully but I get a runtime error:

```
$ ./cucumber_run test.cmxs test.feature 
ERROR loading plugin: error loading shared library: dlopen(/Users/thegaram/cucumber.ml/test.cmxs, 10): Symbol not found: _camlCamlinternalOO__create_object_opt_1533
  Referenced from: /Users/thegaram/cucumber.ml/test.cmxs
  Expected in: flat namespace
 in /Users/thegaram/cucumber.ml/test.cmxs
Fatal error: exception Dynlink.Error(_)
```

[This](https://discuss.ocaml.org/t/fail-to-dynamically-link-cmxs-file-when-using-dynlink/655/15) discussion suggests that parts of the standard library are not linked automatically, so I recompiled like this:

```
ocamlfind opt -shared -package re,re.perl,cucumber,core -linkpkg -o test.cmxs test/test.ml
```

This way I got a different error:

```
$ ./cucumber_run test.cmxs test.feature 
ERROR loading plugin: error loading shared library: dlopen(/Users/thegaram/cucumber.ml/test.cmxs, 10): Symbol not found: _camlCallback__register_exception_1063
  Referenced from: /Users/thegaram/cucumber.ml/test.cmxs
  Expected in: flat namespace
 in /Users/thegaram/cucumber.ml/test.cmxs
Fatal error: exception Dynlink.Error(_)
```

This is not strictly related to this projects, I think it's a peculiarity of Dynlink. I was wondering if you can give me any pointers as to what libraries I need to link to be able to use objects?

**Comment by cyocum** [comment] 2018-03-15 14:15
Not off the top of my head.  Once I have nailed down the other problems you have identified, I will have a look at this.  Thanks!

**Comment by cyocum** [comment] 2018-03-15 18:31
I have opened up an OCaml discussion topic on this problem [here](https://discuss.ocaml.org/t/objects-and-dynlink/1720).

**Comment by cyocum** [comment] 2018-03-16 10:13
@Thegaram After posting this problem to the discussion board, I have a fix.  Could you try this on your end and let me know if this also works for you?

**Comment by cyocum** [comment] 2018-03-17 11:10
I now cannot reproduce the problem :( so I am reopening this because something very odd is going on here.

**Comment by cyocum** [comment] 2018-03-20 11:26
@Thegaram I have created a [branch](https://github.com/cucumber/cucumber.ml/tree/linking) that should solve this problem (it does on my machine).  I also make a few other changes for library support.  Let me know what you think.

**Comment by Thegaram** [comment] 2018-03-20 11:37
@cyocum [linking](https://github.com/cucumber/cucumber.ml/tree/linking) seems to be identical to master. I think you accidentally committed your changes to the [async](https://github.com/cucumber/cucumber.ml/tree/async) branch (07dbab2dfff0f73b43ad026c2221c6452187ef3b).

Also, I think `-linkall` is only needed for `build_runtime` (at least it works fine for me this way).

**Comment by cyocum** [comment] 2018-03-20 11:55
Apologies, I am working quickly today and forgot to commit the changes so the changes should be there now.  Have another look and let me know.  The key insight is that -linkall and -linkpkg have to be done together and I didn't know this until I looked at ocamlfind's documentation more closely.

**Comment by cyocum** [comment] 2018-03-20 19:52
Ok, it looks like the fix I have merged in has fixed the problem. Please feel free to re-open if you have problems.

**Closed as completed by cyocum** 2018-03-20 19:52 UTC
